version: 2.0
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: nikolaik/python-nodejs

    working_directory: ~/medilearn

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      #- run: yarn run test

  deploy:
    docker:
      # specify the version you desire here
      - image: nikolaik/python-nodejs

    working_directory: ~/medilearn

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
         keys:
         - v1-dependencies-{{ checksum "package.json" }}
         # fallback to using the latest cache if no exact match is found
         - v1-dependencies-

      - run: yarn install
      # install AWSCLI to upload to s3 bucket
      - run:
         command: |
           pip install awscli

      - save_cache:
         paths:
           - node_modules
         key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn run build
      # - run: aws s3 sync ~/medilearn/dist s3://$AWS_S3_BUCKET_NAME --delete

workflows:
  version: 2
  test_build_and_deploy:
    jobs:
      - test:
          filters:
            branches:
              only:
                - other-master
                - dev
      - deploy:
          requires:
           - test
          filters:
            branches:
              only: other-master
